"""create wind data

Revision ID: 4e63ce5995ce
Revises: 
Create Date: 2025-11-05 12:15:17.575901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e63ce5995ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wind_turbines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reference_height', sa.Float(), nullable=True),
    sa.Column('hub_height', sa.Float(), nullable=True),
    sa.Column('shear_exp', sa.Float(), nullable=True),
    sa.Column('rotor_diameter', sa.Float(), nullable=True),
    sa.Column('rated_power_kw', sa.Float(), nullable=True),
    sa.Column('cut_in', sa.Float(), nullable=True),
    sa.Column('rated_wind', sa.Float(), nullable=True),
    sa.Column('cut_out', sa.Float(), nullable=True),
    sa.Column('cp', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('air_density_sea_level', sa.Float(), nullable=True),
    sa.Column('mean_wind_annual', sa.Float(), nullable=True),
    sa.Column('weibull_k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_wind_turbines_id'), 'wind_turbines', ['id'], unique=False)
    op.create_table('wind_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbine_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wind_speed_ref', sa.Float(), nullable=True),
    sa.Column('wind_speed_hub', sa.Float(), nullable=True),
    sa.Column('power_raw_W', sa.Float(), nullable=True),
    sa.Column('power_curve_W', sa.Float(), nullable=True),
    sa.Column('power_ac_W', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('turbine_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['turbine_id'], ['wind_turbines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_data_id'), 'wind_data', ['id'], unique=False)
    op.create_index(op.f('ix_wind_data_timestamp'), 'wind_data', ['timestamp'], unique=False)
    op.create_table('wind_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turbine_id', sa.Integer(), nullable=True),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wind_speed_forecast', sa.Float(), nullable=True),
    sa.Column('wind_power_kw_forecast', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['turbine_id'], ['wind_turbines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_forecasts_forecast_time'), 'wind_forecasts', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_wind_forecasts_id'), 'wind_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_wind_forecasts_target_time'), 'wind_forecasts', ['target_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wind_forecasts_target_time'), table_name='wind_forecasts')
    op.drop_index(op.f('ix_wind_forecasts_id'), table_name='wind_forecasts')
    op.drop_index(op.f('ix_wind_forecasts_forecast_time'), table_name='wind_forecasts')
    op.drop_table('wind_forecasts')
    op.drop_index(op.f('ix_wind_data_timestamp'), table_name='wind_data')
    op.drop_index(op.f('ix_wind_data_id'), table_name='wind_data')
    op.drop_table('wind_data')
    op.drop_index(op.f('ix_wind_turbines_id'), table_name='wind_turbines')
    op.drop_table('wind_turbines')
    # ### end Alembic commands ###
