"""consumer data

Revision ID: 6f791e6672b0
Revises: 726178878922
Create Date: 2025-11-05 12:45:36.769448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f791e6672b0'
down_revision: Union[str, Sequence[str], None] = '726178878922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rated_power_kw', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('flexibility', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumers_id'), 'consumers', ['id'], unique=False)
    op.create_table('consumer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('load_kw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_data_id'), 'consumer_data', ['id'], unique=False)
    op.create_index(op.f('ix_consumer_data_timestamp'), 'consumer_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumer_data_timestamp'), table_name='consumer_data')
    op.drop_index(op.f('ix_consumer_data_id'), table_name='consumer_data')
    op.drop_table('consumer_data')
    op.drop_index(op.f('ix_consumers_id'), table_name='consumers')
    op.drop_table('consumers')
    # ### end Alembic commands ###
