"""solar data

Revision ID: 726178878922
Revises: 4e63ce5995ce
Create Date: 2025-11-05 12:22:29.915623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726178878922'
down_revision: Union[str, Sequence[str], None] = '4e63ce5995ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('tilt', sa.Float(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('target_kw', sa.Float(), nullable=True),
    sa.Column('module_power_stc', sa.Float(), nullable=True),
    sa.Column('albedo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_systems_id'), 'solar_systems', ['id'], unique=False)
    op.create_table('solar_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ghi', sa.Float(), nullable=True),
    sa.Column('dni', sa.Float(), nullable=True),
    sa.Column('dhi', sa.Float(), nullable=True),
    sa.Column('poa_global', sa.Float(), nullable=True),
    sa.Column('temp_air', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('temp_cell', sa.Float(), nullable=True),
    sa.Column('dc_power', sa.Float(), nullable=True),
    sa.Column('ac_power', sa.Float(), nullable=True),
    sa.Column('cloud_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['solar_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_data_id'), 'solar_data', ['id'], unique=False)
    op.create_index(op.f('ix_solar_data_timestamp'), 'solar_data', ['timestamp'], unique=False)
    op.create_table('solar_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('horizon_hours', sa.Integer(), nullable=True),
    sa.Column('predicted_power', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['solar_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_forecasts_id'), 'solar_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_solar_forecasts_timestamp'), 'solar_forecasts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_forecasts_timestamp'), table_name='solar_forecasts')
    op.drop_index(op.f('ix_solar_forecasts_id'), table_name='solar_forecasts')
    op.drop_table('solar_forecasts')
    op.drop_index(op.f('ix_solar_data_timestamp'), table_name='solar_data')
    op.drop_index(op.f('ix_solar_data_id'), table_name='solar_data')
    op.drop_table('solar_data')
    op.drop_index(op.f('ix_solar_systems_id'), table_name='solar_systems')
    op.drop_table('solar_systems')
    # ### end Alembic commands ###
