"""init

Revision ID: 80eddb34b03e
Revises: 
Create Date: 2025-12-26 11:19:30.698730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80eddb34b03e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_turbine_data')
    op.add_column('wind_data', sa.Column('wind_turbine_id', sa.Integer(), nullable=False))
    op.add_column('wind_data', sa.Column('wind_speed', sa.Float(), nullable=False))
    op.add_column('wind_data', sa.Column('rotor_diameter_m', sa.Float(), nullable=False))
    op.add_column('wind_data', sa.Column('rated_power_W', sa.Float(), nullable=False))
    op.add_column('wind_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('wind_data', 'wind_speed_ref',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('wind_data', 'power_raw_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('wind_data', 'power_curve_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('wind_data', 'power_ac_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('wind_data', 'rho',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_wind_data_id'), table_name='wind_data')
    op.drop_index(op.f('ix_wind_data_timestamp'), table_name='wind_data')
    op.drop_constraint(op.f('wind_data_turbine_id_fkey'), 'wind_data', type_='foreignkey')
    op.create_foreign_key(None, 'wind_data', 'wind_turbines', ['wind_turbine_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wind_data', 'wind_speed_hub')
    op.drop_column('wind_data', 'turbine_status')
    op.drop_column('wind_data', 'timestamp')
    op.drop_column('wind_data', 'turbine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind_data', sa.Column('turbine_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wind_data', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('wind_data', sa.Column('turbine_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('wind_data', sa.Column('wind_speed_hub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wind_data', type_='foreignkey')
    op.create_foreign_key(op.f('wind_data_turbine_id_fkey'), 'wind_data', 'wind_turbines', ['turbine_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_wind_data_timestamp'), 'wind_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_wind_data_id'), 'wind_data', ['id'], unique=False)
    op.alter_column('wind_data', 'rho',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wind_data', 'power_ac_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wind_data', 'power_curve_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wind_data', 'power_raw_W',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('wind_data', 'wind_speed_ref',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('wind_data', 'created_at')
    op.drop_column('wind_data', 'rated_power_W')
    op.drop_column('wind_data', 'rotor_diameter_m')
    op.drop_column('wind_data', 'wind_speed')
    op.drop_column('wind_data', 'wind_turbine_id')
    op.create_table('wind_turbine_data',
    sa.Column('wind_speed_ref', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('power_raw_W', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('power_curve_W', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('power_ac_W', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rho', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rotor_diameter_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rated_power_W', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
