"""init

Revision ID: e4ecf2dff3a8
Revises: 80eddb34b03e
Create Date: 2025-12-26 11:20:12.201310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ecf2dff3a8'
down_revision: Union[str, Sequence[str], None] = '80eddb34b03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_solar_data_timestamp'), table_name='solar_data')
    op.create_index(op.f('ix_solar_data_created_at'), 'solar_data', ['created_at'], unique=False)
    op.drop_column('solar_data', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_data', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_solar_data_created_at'), table_name='solar_data')
    op.create_index(op.f('ix_solar_data_timestamp'), 'solar_data', ['timestamp'], unique=False)
    op.drop_column('solar_data', 'created_at')
    # ### end Alembic commands ###
