"""init

Revision ID: eeb87581572f
Revises: e4ecf2dff3a8
Create Date: 2025-12-26 11:37:51.245981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb87581572f'
down_revision: Union[str, Sequence[str], None] = 'e4ecf2dff3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_systems', sa.Column('power_kw', sa.Float(), nullable=True))
    op.add_column('solar_systems', sa.Column('efficiency', sa.Float(), nullable=True))
    op.add_column('solar_systems', sa.Column('status', sa.String(length=32), nullable=True))
    op.alter_column('solar_systems', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_column('solar_systems', 'module_power_stc')
    op.drop_column('solar_systems', 'tilt')
    op.drop_column('solar_systems', 'timezone')
    op.drop_column('solar_systems', 'albedo')
    op.drop_column('solar_systems', 'longitude')
    op.drop_column('solar_systems', 'latitude')
    op.drop_column('solar_systems', 'target_kw')
    op.drop_column('solar_systems', 'azimuth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solar_systems', sa.Column('azimuth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('target_kw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('albedo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('tilt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('solar_systems', sa.Column('module_power_stc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('solar_systems', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('solar_systems', 'status')
    op.drop_column('solar_systems', 'efficiency')
    op.drop_column('solar_systems', 'power_kw')
    # ### end Alembic commands ###
